theme = "blowfish"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true
summaryLength = 0

[taxonomies]
  tag = "tags"
  category = "categories"

[caches]
  [caches.images]
    dir = ":cacheDir/images"